from enum import Enum


class ACTIVITY_TYPE(Enum):
    COURSES = "COURSES"
    LECTURES = "LECTURES"
    HIGH_IMPACT_LECTURES = "HIGH_IMPACT_LECTURES"
    TECHNICAL_VISITS = "TECHNICAL_VISITS"
    ACADEMIC_COMPETITIONS = "ACADEMIC_COMPETITIONS"
    HACKATHON = "HACKATHON"
    INTERNSHIP_FAIR = "INTERNSHIP_FAIR"
    ALUMNI_CAFE = "ALUMNI_CAFE"
    PROFESSORS_ACADEMY = "PROFESSORS_ACADEMY"
    CULTURAL_ACTIVITY = "CULTURAL_ACTIVITY"
    GCSP = "GCSP"
    SPORTS_ACTIVITY = "SPORTS_ACTIVITY"
    MAUA_PLUS = "MAUA_PLUS"
    PANELS = "PANELS"
    INTERNATIONAL_WORKSHOP = "INTERNATIONAL_WORKSHOP"
    ENGINEERING = "ENGINEERING"
