from enum import Enum


class ROLE(Enum):
    STUDENT = "STUDENT"
    ADMIN = "ADMIN"
    EMPLOYEE = "EMPLOYEE"
    PROFESSOR = "PROFESSOR"
    INTERNATIONAL_STUDENT = "INTERNATIONAL_STUDENT"
    EXTERNAL = "EXTERNAL"
